// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7NjQ7E2OJvc3OpSQ0SeI1M1lNXtr2RJo',
    appId: '1:906363728709:web:c9971e1e515fadda4f042c',
    messagingSenderId: '906363728709',
    projectId: 'marriage-era-70868',
    authDomain: 'marriage-era-70868.firebaseapp.com',
    storageBucket: 'marriage-era-70868.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNaN4fraJO2vUCrRaRGU4zV88y5tfHD9o',
    appId: '1:906363728709:android:ae94d00e6520afa14f042c',
    messagingSenderId: '906363728709',
    projectId: 'marriage-era-70868',
    storageBucket: 'marriage-era-70868.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ9gQs8b2E9oBt_spCW6H6VtdqA6xIr-k',
    appId: '1:906363728709:ios:b37fb49ac8d240ad4f042c',
    messagingSenderId: '906363728709',
    projectId: 'marriage-era-70868',
    storageBucket: 'marriage-era-70868.firebasestorage.app',
    iosBundleId: 'com.example.vm24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ9gQs8b2E9oBt_spCW6H6VtdqA6xIr-k',
    appId: '1:906363728709:ios:b37fb49ac8d240ad4f042c',
    messagingSenderId: '906363728709',
    projectId: 'marriage-era-70868',
    storageBucket: 'marriage-era-70868.firebasestorage.app',
    iosBundleId: 'com.example.vm24',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7NjQ7E2OJvc3OpSQ0SeI1M1lNXtr2RJo',
    appId: '1:906363728709:web:68558f15fd4bb65d4f042c',
    messagingSenderId: '906363728709',
    projectId: 'marriage-era-70868',
    authDomain: 'marriage-era-70868.firebaseapp.com',
    storageBucket: 'marriage-era-70868.firebasestorage.app',
  );
}
